import gradio as gr
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Default system message
DEFAULT_SYSTEM_MSG = "You are a helpful AI assistant."

def predict(message, history, system_message):
    """
    Process user message and generate a response.
    
    Args:
        message: User's input message
        history: Chat history
        system_message: System instruction for the assistant
        
    Returns:
        Updated message and history
    """
    # Don't process empty messages
    if not message or message.strip() == "":
        return "", history
    
    # Add user message to history
    history.append({"role": "user", "content": message})
    
    # Generate a simple response (in a real app, this would call an AI model)
    if system_message and "comedian" in system_message.lower():
        response = "Here's a joke: Why don't scientists trust atoms? Because they make up everything!"
    else:
        response = f"You said: {message}\n\nThis is a template response. In a real application, this would be generated by an AI model."
    
    # Add assistant response to history
    history.append({"role": "assistant", "content": response})
    
    return "", history

# Create the Gradio Blocks interface
with gr.Blocks(theme=gr.themes.Monochrome()) as demo:
    gr.Markdown("# Basic Chatbot Template")
    
    with gr.Row():
        with gr.Column(scale=4):
            chatbot = gr.Chatbot(type="messages", height=500)
            msg = gr.Textbox(placeholder="Type your message here...", label="Your message")
            with gr.Row():
                clear = gr.ClearButton([msg, chatbot], value="Clear chat")
                submit_btn = gr.Button("Submit", variant="primary")
        
        with gr.Column(scale=1):
            system_msg = gr.Textbox(
                label="System Message", 
                placeholder="Set the AI's behavior...",
                value=DEFAULT_SYSTEM_MSG,
                lines=3
            )
    
    with gr.Accordion("Examples", open=False):
        gr.Examples(
            examples=[
                ["Tell me about artificial intelligence", DEFAULT_SYSTEM_MSG],
                ["Write a short poem about nature", DEFAULT_SYSTEM_MSG],
                ["Tell me a joke", "You are a comedian who specializes in clean, family-friendly humor."]
            ],
            inputs=[msg, system_msg],
        )
    
    # Event handlers
    msg.submit(predict, [msg, chatbot, system_msg], [msg, chatbot])
    submit_btn.click(predict, [msg, chatbot, system_msg], [msg, chatbot])

# Launch the app
if __name__ == "__main__":
    demo.launch()
